// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtcutz6zEBIlk5AJWYw0Q3IKf9mc5ocLI',
    appId: '1:289092472788:web:6a26777bd0555992035041',
    messagingSenderId: '289092472788',
    projectId: 'tmdb-app-4e10a',
    authDomain: 'tmdb-app-4e10a.firebaseapp.com',
    storageBucket: 'tmdb-app-4e10a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6eSOtzKEZ8nOY8rFPxSfKyjP1aI3Ruk0',
    appId: '1:289092472788:android:5141ccc4a3c8b879035041',
    messagingSenderId: '289092472788',
    projectId: 'tmdb-app-4e10a',
    storageBucket: 'tmdb-app-4e10a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdQ2vgx3g3fVtWc_dz9F8wyUlvjCfXr9k',
    appId: '1:289092472788:ios:003e730488d82c3f035041',
    messagingSenderId: '289092472788',
    projectId: 'tmdb-app-4e10a',
    storageBucket: 'tmdb-app-4e10a.appspot.com',
    iosBundleId: 'com.example.tmdbApp',
  );
}
